language: node_js

before_install:
  - npm install -g npm@latest

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

script:
  - npm run lint
  - npm test

after_success:
  - npm run test:coverage
